### ISSUE TITLE
Removing the ability to build

### ISSUE THREAD

**Issue by alexcroox** [kami-/plank#2]
I'd like to build a mission where players get time at the start to build some defenses around a town, after a certain amount of time I'd like to remove the scroll wheel options for them so they can't spawn anything else, is this possible?

**Comment by kami-** [comment]
Will push a WIP version today.

**Comment by kami-** [comment]
You can now remove fortifications with `plank_api_fnc_forceRemoveAllFortifications`. Also beware, I've added a separate API functions file, which will contains all available functions. Use `plank_api_fnc_forceAddFortifications` instead of `plank_deploy_fnc_init`.
