### ISSUE TITLE
Script possibly broken in recent updates

### ISSUE THREAD

**Issue by QuintusGARS** [kami-/plank#3]
Hello! I've tried to include your nice script into a mission, in a version of the F3 format but I can't make it work at all, despite following the steps you wrote in the prerequisite. 

It might have to be caused by recent arma updates but I have no competence in saying what, I barely understand how to make a pre-made script work, I'm a complete scrub on anything else. Do you feel like trying to patch this up? I'd really love to use it with my Arma team.

Thanks for your time and sorry for my crappy english.

**Comment by kami-** [comment]
Hi!
Please upload your mission somewhere and I will take a look at it.

**Comment by QuintusGARS** [comment]
Note: i've put your code on line 341 on the description.ext because when I use wolfenswan funciton -designed for F3 template- it's reccomanded to do it that way.
In the init.sqf instead I placed it to the bottom.
The unit supposed to deploy the fortifications is the engenieer squadleader, in his init field I've tried several combination of your prerequisite n.4 point (like: [player, [2, 1, 2, 2, 0, 2, 0, 0]] call plank_api_fnc_forceAddFortifications; [this, [2, 1, 2, 2, 0, 2, 0, 0]] call etc.; [< name of the unit >, [2, 1, 2, 2, 0, 2, 0, 0]] call etc.;) with no luck.

https://www.dropbox.com/sh/p9wui3xahafh2jl/AAD52jpLSu5-MWTsNaEGdnKGa?dl=0

Here's the whole folder of the mission -absolutely a WIP- since it's faster to check what's wrong if you have all the files involved.

Thanks in advance!!

**Comment by kami-** [comment]
So I can't run it as I'm missing addons. However I think I found the issue.
`mission.sqm` line 341, you have included Plank inside the `CfgFunctions` class. Plank needs to be included in the root of `description.ext`.

**Comment by QuintusGARS** [comment]
So like in the first line?

**Comment by kami-** [comment]
Yes, first line works.

**Comment by QuintusGARS** [comment]
Thanks a lot for your help then! As always it's the simple mistakes that get me. I'm gonna test it tomorrow if any issues arises.

**Comment by QuintusGARS** [comment]
Finally got what was wrong. Now it works perfectly. Thanks a lot!
